# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: cicd-nodejs

on:
  push: 
    branches: [ main ]
jobs:
  push_to_registry: 
    name: push docker hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker Login
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
      - name: Build Docker 
        run: |
          docker build . -t mheak/nodejs-numerical:latest
      - name: Push to Docker
        run: |
          docker push mheak/nodejs-numerical:latest
